# Generated by Django 6.0.5 on 2026-06-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_completed_at_event_is_completed_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completion_note',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
